import { CountryInfo } from '../types';

export const REGIONS: Record<string, string[]> = {
  'North America': ['US', 'CA', 'MX'],
  'Central America & Caribbean': ['GT', 'BZ', 'SV', 'HN', 'NI', 'CR', 'PA', 'CU', 'JM', 'HT', 'DO', 'PR', 'TT', 'BB', 'BS'],
  'South America': ['BR', 'AR', 'CO', 'PE', 'VE', 'CL', 'EC', 'BO', 'PY', 'UY', 'GY', 'SR'],
  'Western Europe': ['GB', 'DE', 'FR', 'IT', 'ES', 'PT', 'NL', 'BE', 'CH', 'AT', 'IE', 'LU', 'MC', 'AD', 'MT', 'IS'],
  'Northern Europe': ['SE', 'NO', 'DK', 'FI', 'EE', 'LV', 'LT'],
  'Eastern Europe': ['PL', 'CZ', 'SK', 'HU', 'RO', 'BG', 'UA', 'BY', 'MD', 'RS', 'HR', 'BA', 'SI', 'ME', 'MK', 'AL', 'XK'],
  'Middle East': ['AE', 'SA', 'QA', 'KW', 'BH', 'OM', 'IL', 'JO', 'LB', 'IQ', 'IR', 'YE', 'SY', 'TR', 'CY'],
  'North Africa': ['EG', 'LY', 'TN', 'DZ', 'MA'],
  'Sub-Saharan Africa': ['ZA', 'NG', 'KE', 'GH', 'ET', 'TZ', 'UG', 'CI', 'SN', 'CM', 'MZ', 'AO', 'ZM', 'ZW', 'BW', 'NA', 'MU', 'RW', 'CD', 'MG'],
  'Central Asia': ['KZ', 'UZ', 'TM', 'TJ', 'KG'],
  'South Asia': ['IN', 'PK', 'BD', 'LK', 'NP', 'MM'],
  'East Asia': ['CN', 'JP', 'KR', 'KP', 'MN', 'TW', 'HK', 'MO'],
  'Southeast Asia': ['SG', 'MY', 'TH', 'ID', 'PH', 'VN', 'LA', 'KH', 'BN'],
  'Oceania': ['AU', 'NZ', 'FJ', 'PG', 'WS'],
};

export const COUNTRIES: CountryInfo[] = [
  { code: 'US', name: 'United States', region: 'North America' },
  { code: 'CA', name: 'Canada', region: 'North America' },
  { code: 'MX', name: 'Mexico', region: 'North America' },
  { code: 'GT', name: 'Guatemala', region: 'Central America & Caribbean' },
  { code: 'BZ', name: 'Belize', region: 'Central America & Caribbean' },
  { code: 'SV', name: 'El Salvador', region: 'Central America & Caribbean' },
  { code: 'HN', name: 'Honduras', region: 'Central America & Caribbean' },
  { code: 'NI', name: 'Nicaragua', region: 'Central America & Caribbean' },
  { code: 'CR', name: 'Costa Rica', region: 'Central America & Caribbean' },
  { code: 'PA', name: 'Panama', region: 'Central America & Caribbean' },
  { code: 'CU', name: 'Cuba', region: 'Central America & Caribbean' },
  { code: 'JM', name: 'Jamaica', region: 'Central America & Caribbean' },
  { code: 'HT', name: 'Haiti', region: 'Central America & Caribbean' },
  { code: 'DO', name: 'Dominican Republic', region: 'Central America & Caribbean' },
  { code: 'PR', name: 'Puerto Rico', region: 'Central America & Caribbean' },
  { code: 'TT', name: 'Trinidad and Tobago', region: 'Central America & Caribbean' },
  { code: 'BB', name: 'Barbados', region: 'Central America & Caribbean' },
  { code: 'BS', name: 'Bahamas', region: 'Central America & Caribbean' },
  { code: 'BR', name: 'Brazil', region: 'South America' },
  { code: 'AR', name: 'Argentina', region: 'South America' },
  { code: 'CO', name: 'Colombia', region: 'South America' },
  { code: 'PE', name: 'Peru', region: 'South America' },
  { code: 'VE', name: 'Venezuela', region: 'South America' },
  { code: 'CL', name: 'Chile', region: 'South America' },
  { code: 'EC', name: 'Ecuador', region: 'South America' },
  { code: 'BO', name: 'Bolivia', region: 'South America' },
  { code: 'PY', name: 'Paraguay', region: 'South America' },
  { code: 'UY', name: 'Uruguay', region: 'South America' },
  { code: 'GY', name: 'Guyana', region: 'South America' },
  { code: 'SR', name: 'Suriname', region: 'South America' },
  { code: 'GB', name: 'United Kingdom', region: 'Western Europe' },
  { code: 'DE', name: 'Germany', region: 'Western Europe' },
  { code: 'FR', name: 'France', region: 'Western Europe' },
  { code: 'IT', name: 'Italy', region: 'Western Europe' },
  { code: 'ES', name: 'Spain', region: 'Western Europe' },
  { code: 'PT', name: 'Portugal', region: 'Western Europe' },
  { code: 'NL', name: 'Netherlands', region: 'Western Europe' },
  { code: 'BE', name: 'Belgium', region: 'Western Europe' },
  { code: 'CH', name: 'Switzerland', region: 'Western Europe' },
  { code: 'AT', name: 'Austria', region: 'Western Europe' },
  { code: 'IE', name: 'Ireland', region: 'Western Europe' },
  { code: 'LU', name: 'Luxembourg', region: 'Western Europe' },
  { code: 'MC', name: 'Monaco', region: 'Western Europe' },
  { code: 'AD', name: 'Andorra', region: 'Western Europe' },
  { code: 'MT', name: 'Malta', region: 'Western Europe' },
  { code: 'IS', name: 'Iceland', region: 'Western Europe' },
  { code: 'SE', name: 'Sweden', region: 'Northern Europe' },
  { code: 'NO', name: 'Norway', region: 'Northern Europe' },
  { code: 'DK', name: 'Denmark', region: 'Northern Europe' },
  { code: 'FI', name: 'Finland', region: 'Northern Europe' },
  { code: 'EE', name: 'Estonia', region: 'Northern Europe' },
  { code: 'LV', name: 'Latvia', region: 'Northern Europe' },
  { code: 'LT', name: 'Lithuania', region: 'Northern Europe' },
  { code: 'PL', name: 'Poland', region: 'Eastern Europe' },
  { code: 'CZ', name: 'Czech Republic', region: 'Eastern Europe' },
  { code: 'SK', name: 'Slovakia', region: 'Eastern Europe' },
  { code: 'HU', name: 'Hungary', region: 'Eastern Europe' },
  { code: 'RO', name: 'Romania', region: 'Eastern Europe' },
  { code: 'BG', name: 'Bulgaria', region: 'Eastern Europe' },
  { code: 'UA', name: 'Ukraine', region: 'Eastern Europe' },
  { code: 'BY', name: 'Belarus', region: 'Eastern Europe' },
  { code: 'MD', name: 'Moldova', region: 'Eastern Europe' },
  { code: 'RS', name: 'Serbia', region: 'Eastern Europe' },
  { code: 'HR', name: 'Croatia', region: 'Eastern Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'Eastern Europe' },
  { code: 'SI', name: 'Slovenia', region: 'Eastern Europe' },
  { code: 'ME', name: 'Montenegro', region: 'Eastern Europe' },
  { code: 'MK', name: 'North Macedonia', region: 'Eastern Europe' },
  { code: 'AL', name: 'Albania', region: 'Eastern Europe' },
  { code: 'XK', name: 'Kosovo', region: 'Eastern Europe' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Middle East' },
  { code: 'QA', name: 'Qatar', region: 'Middle East' },
  { code: 'KW', name: 'Kuwait', region: 'Middle East' },
  { code: 'BH', name: 'Bahrain', region: 'Middle East' },
  { code: 'OM', name: 'Oman', region: 'Middle East' },
  { code: 'IL', name: 'Israel', region: 'Middle East' },
  { code: 'JO', name: 'Jordan', region: 'Middle East' },
  { code: 'LB', name: 'Lebanon', region: 'Middle East' },
  { code: 'IQ', name: 'Iraq', region: 'Middle East' },
  { code: 'IR', name: 'Iran', region: 'Middle East' },
  { code: 'YE', name: 'Yemen', region: 'Middle East' },
  { code: 'SY', name: 'Syria', region: 'Middle East' },
  { code: 'TR', name: 'Turkey', region: 'Middle East' },
  { code: 'CY', name: 'Cyprus', region: 'Middle East' },
  { code: 'EG', name: 'Egypt', region: 'North Africa' },
  { code: 'LY', name: 'Libya', region: 'North Africa' },
  { code: 'TN', name: 'Tunisia', region: 'North Africa' },
  { code: 'DZ', name: 'Algeria', region: 'North Africa' },
  { code: 'MA', name: 'Morocco', region: 'North Africa' },
  { code: 'ZA', name: 'South Africa', region: 'Sub-Saharan Africa' },
  { code: 'NG', name: 'Nigeria', region: 'Sub-Saharan Africa' },
  { code: 'KE', name: 'Kenya', region: 'Sub-Saharan Africa' },
  { code: 'GH', name: 'Ghana', region: 'Sub-Saharan Africa' },
  { code: 'ET', name: 'Ethiopia', region: 'Sub-Saharan Africa' },
  { code: 'TZ', name: 'Tanzania', region: 'Sub-Saharan Africa' },
  { code: 'UG', name: 'Uganda', region: 'Sub-Saharan Africa' },
  { code: 'CI', name: "Côte d'Ivoire", region: 'Sub-Saharan Africa' },
  { code: 'SN', name: 'Senegal', region: 'Sub-Saharan Africa' },
  { code: 'CM', name: 'Cameroon', region: 'Sub-Saharan Africa' },
  { code: 'MZ', name: 'Mozambique', region: 'Sub-Saharan Africa' },
  { code: 'AO', name: 'Angola', region: 'Sub-Saharan Africa' },
  { code: 'ZM', name: 'Zambia', region: 'Sub-Saharan Africa' },
  { code: 'ZW', name: 'Zimbabwe', region: 'Sub-Saharan Africa' },
  { code: 'BW', name: 'Botswana', region: 'Sub-Saharan Africa' },
  { code: 'NA', name: 'Namibia', region: 'Sub-Saharan Africa' },
  { code: 'MU', name: 'Mauritius', region: 'Sub-Saharan Africa' },
  { code: 'RW', name: 'Rwanda', region: 'Sub-Saharan Africa' },
  { code: 'CD', name: 'DR Congo', region: 'Sub-Saharan Africa' },
  { code: 'MG', name: 'Madagascar', region: 'Sub-Saharan Africa' },
  { code: 'KZ', name: 'Kazakhstan', region: 'Central Asia' },
  { code: 'UZ', name: 'Uzbekistan', region: 'Central Asia' },
  { code: 'TM', name: 'Turkmenistan', region: 'Central Asia' },
  { code: 'TJ', name: 'Tajikistan', region: 'Central Asia' },
  { code: 'KG', name: 'Kyrgyzstan', region: 'Central Asia' },
  { code: 'IN', name: 'India', region: 'South Asia' },
  { code: 'PK', name: 'Pakistan', region: 'South Asia' },
  { code: 'BD', name: 'Bangladesh', region: 'South Asia' },
  { code: 'LK', name: 'Sri Lanka', region: 'South Asia' },
  { code: 'NP', name: 'Nepal', region: 'South Asia' },
  { code: 'MM', name: 'Myanmar', region: 'South Asia' },
  { code: 'CN', name: 'China', region: 'East Asia' },
  { code: 'JP', name: 'Japan', region: 'East Asia' },
  { code: 'KR', name: 'South Korea', region: 'East Asia' },
  { code: 'KP', name: 'North Korea', region: 'East Asia' },
  { code: 'MN', name: 'Mongolia', region: 'East Asia' },
  { code: 'TW', name: 'Taiwan', region: 'East Asia' },
  { code: 'HK', name: 'Hong Kong', region: 'East Asia' },
  { code: 'MO', name: 'Macau', region: 'East Asia' },
  { code: 'SG', name: 'Singapore', region: 'Southeast Asia' },
  { code: 'MY', name: 'Malaysia', region: 'Southeast Asia' },
  { code: 'TH', name: 'Thailand', region: 'Southeast Asia' },
  { code: 'ID', name: 'Indonesia', region: 'Southeast Asia' },
  { code: 'PH', name: 'Philippines', region: 'Southeast Asia' },
  { code: 'VN', name: 'Vietnam', region: 'Southeast Asia' },
  { code: 'LA', name: 'Laos', region: 'Southeast Asia' },
  { code: 'KH', name: 'Cambodia', region: 'Southeast Asia' },
  { code: 'BN', name: 'Brunei', region: 'Southeast Asia' },
  { code: 'AU', name: 'Australia', region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania' },
  { code: 'FJ', name: 'Fiji', region: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', region: 'Oceania' },
  { code: 'WS', name: 'Samoa', region: 'Oceania' },
];

const countryMap = new Map(COUNTRIES.map(c => [c.code, c]));

export function getCountryInfo(code: string): CountryInfo | undefined {
  return countryMap.get(code);
}

export function getRegionForCountry(code: string): string | undefined {
  return countryMap.get(code)?.region;
}

export function getRegionsForCountries(codes: string[]): string[] {
  if (codes.includes('GLOBAL')) {
    return Object.keys(REGIONS);
  }
  const regions = new Set<string>();
  for (const code of codes) {
    const region = getRegionForCountry(code);
    if (region) regions.add(region);
  }
  return Array.from(regions);
}
